---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:7701/lessons-db
    username: lessons-user
    password: lessons-pwd-01
    driver-class-name: org.mariadb.jdbc.Driver

