server:
  port: 7000

spring:
  cloud:
    gateway:
      routes:
        - id: prescriptionModule
          uri: http://localhost:7100/
          predicates:
              - Path=/prescription/**
          filters:
              - RewritePath=/prescription(?<segment>/?.*), $\{segment}
        - id: rendezvousModule
          uri: http://localhost:7200/
          predicates:
              - Path=/rendezvous/**
          filters:
              - RewritePath=/rendezvous(?<segment>/?.*), $\{segment}

